# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctk < Formula
  desc "Context Token Killer — compresses Claude Code tool output (MCP, native tools, Bash)"
  homepage "https://github.com/AbhayShalghar/ctk"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AbhayShalghar/ctk/releases/download/v0.1.0/ctk_darwin_amd64.tar.gz"
      sha256 "342582c8432ddc6e2349f3a68fd37103a9176b6d628b982a5b72510274e610b0"

      define_method(:install) do
        bin.install "ctk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AbhayShalghar/ctk/releases/download/v0.1.0/ctk_darwin_arm64.tar.gz"
      sha256 "88b7f81cd706f3a0d20deb8b71afadec26a41dc7ae4b3c15ccf111be722ae2db"

      define_method(:install) do
        bin.install "ctk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AbhayShalghar/ctk/releases/download/v0.1.0/ctk_linux_amd64.tar.gz"
      sha256 "57b43338a9b6cd85ae48e240c1660f6825b02779e587e25791cb3c9dbd64bbb5"
      define_method(:install) do
        bin.install "ctk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AbhayShalghar/ctk/releases/download/v0.1.0/ctk_linux_arm64.tar.gz"
      sha256 "0bbc232127bfacbb059b3c908d4c5df414c9bf2d4946f2caf7c76ea1ce99ea8a"
      define_method(:install) do
        bin.install "ctk"
      end
    end
  end

  test do
    system "#{bin}/ctk", "version"
  end
end
