# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctk" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "879d84f40c57ad6dcab6d3dc04b29f895cd6ffa9850b6d7dcabc9404d0d1c9b0"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b89aa4248261fa7edc71f992f6639770fac2a6b38f8ef0034c0395cfb4c1a4e8"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "44c4aeddc1cba82b1df0196ca6076b1606b892d8ebba2d93f1758296822822ad"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ac17c950fa0ee1bcc6572d4fddf89f42a845d8dbde7fea6ce7ca35afca8fc35"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_linux_arm64.tar.gz"
    end
  end

  name "ctk"
  desc "Context Token Killer — compresses Claude Code tool output (MCP, native tools, Bash)"
  homepage "https://github.com/AbhayShalghar/ctk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctk"]
    end
  end

  # No zap stanza required

end
