# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctk" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "666d65716cab6752056b948d681079a2c8b0eed3caf5ad2d0ef768995d724e1d"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8021cdf819db1c6b8000217bf094e56dae62c7fb3b30308b5aa7cf173ff63c7c"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "adfbb55bd8e1ecfdd4df67e662dd15d075773614b31a5377ef9bdf211f0eba19"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd9549b626fcd47e4bbb025c9c7e1572fc506a0814a87e2b99c37516e9fed270"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_linux_arm64.tar.gz"
    end
  end

  name "ctk"
  desc "Context Token Killer — compresses Claude Code tool output (MCP, native tools, Bash)"
  homepage "https://github.com/AbhayShalghar/ctk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctk"]
    end
  end

  # No zap stanza required

end
