# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctk" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "9e10e3cc620486e19ea75a554962e32208dd197090f64ce5e9ef71823a5beb52"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "00aac647496bcde6e03ae656e1591f7784fd875ddacc1b5e0ed25d44c23d298a"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "848ef4065a535a6754bdf27a52b3376ab8488df09512730ab0ba6b3b7fb75831"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "deacf4746a9c615fcd145088059aaffd4fa5a0606a02223be77dadeaea00fa73"
      url "https://github.com/AbhayShalghar/ctk/releases/download/v#{version}/ctk_linux_arm64.tar.gz"
    end
  end

  name "ctk"
  desc "Context Token Killer — compresses Claude Code tool output (MCP, native tools, Bash)"
  homepage "https://github.com/AbhayShalghar/ctk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctk"]
    end
  end

  # No zap stanza required

end
